In [1]:
import os
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

TRAIN_DATA_FILE = "train_data.csv"
TEST_DATA_FILE = "test_data.csv"
ALL_CASES_INPUT_DATA = "all_cases_input_data.csv"
ALL_CASES_PREDICTIONS = "all_cases_predictions.csv"
ALL_CASES_PREDICTIONS_COLUMS = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

def load_data(file=TRAIN_DATA_FILE, header=True):
    csv_path = os.path.join("", file)
    if header:
        return pd.read_csv(csv_path)
    else:
        return pd.read_csv(csv_path, header=None)

In [2]:
train_data = load_data(TRAIN_DATA_FILE)
train_labels = train_data["DIGIT"]
train_data.drop("DIGIT", axis=1, inplace=True)

test_data = load_data(TEST_DATA_FILE)
test_labels = test_data["DIGIT"]
test_data.drop("DIGIT", axis=1, inplace=True)

all_cases_input_data = load_data(ALL_CASES_INPUT_DATA)

In [3]:
from sklearn.decomposition import PCA

def get_dims_variances(x, minDim, tol=None, thres=0.01):
    dims = []
    variances = []
    optimum_dim = minDim
    prev_min_variance = None
    dim = minDim
    
    while(True):
        pca = PCA(n_components=dim)
        pca.fit(x)
        variance = np.array(pca.explained_variance_ratio_)
        min_variance = variance.min()
        
        dims.append(dim)
        variances.append(min_variance)
        
        if tol != None and prev_min_variance != None and min_variance + tol > prev_min_variance:
            break

        else:
            if prev_min_variance != None and min_variance < thres:
                break
                
        prev_min_variance = min_variance
        optimum_dim = dim
        dim = dim + 1

    return dims, variances, optimum_dim

In [4]:
from sklearn.preprocessing import PolynomialFeatures
def process_data(x, y=None, poly_features=None, pca=None, OPTIMUM_DIMENSION=None):
    training_features = x.copy()
    testing_features = y.copy()
    
    if poly_features == None:
        poly_features = PolynomialFeatures(degree=2, include_bias=False)
        poly_features.fit(training_features)
        
    training_features = poly_features.transform(training_features)
    testing_features = poly_features.transform(testing_features)

    if OPTIMUM_DIMENSION == None:
        dims, variances, OPTIMUM_DIMENSION = get_dims_variances(x=training_features, minDim=2, thres=0.01)
        print("Optimum Dimensions: ", OPTIMUM_DIMENSION)
        import matplotlib.pyplot as plt
        plt.plot(dims, variances)
        plt.show()
        dim_df = pd.DataFrame()
        dim_df["DIM"] = dims
        dim_df["VAR"] = variances
        print(dim_df)

    if pca == None:  
        pca = PCA(random_state=42, n_components=OPTIMUM_DIMENSION)
        pca.fit(training_features)
        
    training_features = pca.transform(training_features)
    testing_features = pca.transform(testing_features)
    
    return training_features, testing_features, poly_features, pca, OPTIMUM_DIMENSION

In [5]:
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import StandardScaler

imputer = Imputer(strategy="median")
training_features = imputer.fit_transform(train_data)
testing_features = imputer.transform(test_data)
all_cases_features = imputer.transform(all_cases_input_data)

scalar = StandardScaler()
training_features = scalar.fit_transform(training_features)
testing_features = scalar.transform(testing_features)
all_cases_features = scalar.transform(all_cases_features)

training_features, testing_features, poly_features, pca, OPTIMUM_DIMENSION = process_data(x=training_features, y=testing_features)

training_labels = train_labels.values
testing_labels = test_labels.values

Optimum Dimensions:  18


    DIM       VAR
0     2  0.126065
1     3  0.091955
2     4  0.078825
3     5  0.072726
4     6  0.062582
5     7  0.052270
6     8  0.047362
7     9  0.044440
8    10  0.042660
9    11  0.036638
10   12  0.030894
11   13  0.025990
12   14  0.022621
13   15  0.016864
14   16  0.013965
15   17  0.011354
16   18  0.010331
17   19  0.006118


In [6]:
# SGD Classifier
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.base import clone

X_train = training_features
Y_train = training_labels
X_test = testing_features
Y_test = testing_labels

sgd_clf = SGDClassifier(random_state=42, penalty="l1")
cross_val_scores = cross_val_score(clone(sgd_clf), X_train, Y_train, cv=2, scoring="accuracy")
print("Cross Val Scores on training set\n", cross_val_scores)

sgd_clf.fit(X_train, Y_train)
print("\n\nAccuracy on testing data set\n", sum(Y_test == sgd_clf.predict(X_test)) / len(Y_test))

Cross Val Scores on training set
 [0.6 0.4]


Accuracy on testing data set
 0.9


In [7]:
# KNeighbors Classifier
from sklearn.neighbors import KNeighborsClassifier 

X_train = training_features
Y_train = training_labels
X_test = testing_features
Y_test = testing_labels

parameters = {'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
              'n_neighbors' : [2,3,4,5,6,7,8,9,10],
              'weights' : ['uniform', 'distance']
             }
clf = GridSearchCV(KNeighborsClassifier(), parameters)
clf.fit(X_train, Y_train)
print("\nBest params: ", clf.best_params_)

knn_clf = KNeighborsClassifier(algorithm='auto', n_neighbors=2, weights='uniform')
print("\nCross Val Scores on training set\n", cross_val_score(clone(knn_clf), X_train, Y_train, cv=2, scoring="accuracy"))

knn_clf.fit(X_train, Y_train)
print("\n\nAccuracy on testing data set\n", sum(Y_test == clf.predict(X_test)) / len(Y_test))


Best params:  {'algorithm': 'auto', 'n_neighbors': 2, 'weights': 'distance'}

Cross Val Scores on training set
 [0.5 0.5]


Accuracy on testing data set
 0.9


In [8]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier 

X_train = training_features
Y_train = training_labels
X_test = testing_features
Y_test = testing_labels

forest_clf = RandomForestClassifier(random_state=42, oob_score=True, n_estimators=5)
print("Cross Val Scores on training set\n", cross_val_score(clone(forest_clf), X_train, Y_train, cv=2, scoring="accuracy"))

forest_clf.fit(X_train, Y_train)
print("\n\nAccuracy on testing data set\n", sum(Y_test == forest_clf.predict(X_test)) / len(Y_test))

Cross Val Scores on training set
 [0.15 0.1 ]


Accuracy on testing data set
 0.95


In [9]:
# MLP Classifier
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
from sklearn.preprocessing import LabelBinarizer

X_train = training_features
Y_train = training_labels
X_test = testing_features
Y_test = testing_labels
batch_size = 3
num_classes = 10
epochs = 15

model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.8))
model.add(Dense(num_classes, activation='softmax'))

model.summary()

adam = Adam()
model.compile(loss='categorical_crossentropy',
              optimizer=adam,
              metrics=['accuracy'])

binarizer = LabelBinarizer()
binarizer.fit(Y_train)
Y_train = binarizer.transform(Y_train)
Y_test = binarizer.transform(Y_test)

history = model.fit(X_train, Y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, Y_test))

score = model.evaluate(X_test, Y_test, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
print('Test accuracy/loss ratio:', score[1] / score[0])

Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 256)               4864      
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                2570      
Total params: 7,434
Trainable params: 7,434
Non-trainable params: 0
_________________________________________________________________
Train on 30 samples, validate on 20 samples
Epoch 1/15
30/30 [==============================] - 0s 10ms/step - loss: 2.7779 - acc: 0.0667 - val_loss: 2.5596 - val_acc: 0.0500
Epoch 2/15
30/30 [==============================] - 0s 710us/step - loss: 2.8183 - acc: 0.1667 - val_loss: 2.4088 - val_acc: 0.1000
Epoch 3/15
30/30 [==============================] - 0s 716us/step - loss: 2.8517 - acc: 0.0667 - 

In [10]:
x = [[0,0,0,1,0,0,0]]
x_,_,_,_,_ = process_data(x=x, y=x, poly_features=poly_features, pca=pca, OPTIMUM_DIMENSION=OPTIMUM_DIMENSION)
print(model.predict(x_.copy()))
print(forest_clf.predict_proba(x_.copy()))
print(knn_clf.predict_proba(x_.copy()))
print(sgd_clf.predict(x_.copy()))

[[0.11031048 0.06208147 0.11678445 0.11123959 0.08184429 0.11866929
  0.1073188  0.06332638 0.09520247 0.13322277]]
[[0.  0.4 0.  0.  0.2 0.  0.  0.  0.2 0.2]]
[[0.  0.  0.  0.  0.  0.5 0.  0.  0.  0.5]]
[5]


In [11]:
x = [[0,1,0,1,0,0,0]]
x_,_,_,_,_ = process_data(x=x, y=x, poly_features=poly_features, pca=pca, OPTIMUM_DIMENSION=OPTIMUM_DIMENSION)
print(model.predict(x_.copy()))
print(forest_clf.predict_proba(x_.copy()))
print(knn_clf.predict_proba(x_.copy()))
print(sgd_clf.predict(x_.copy()))

[[0.1054697  0.0578808  0.10781884 0.13407862 0.09722768 0.10026815
  0.08649302 0.0578361  0.10698884 0.1459383 ]]
[[0.  0.2 0.2 0.  0.  0.  0.  0.  0.2 0.4]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[3]


In [33]:
def get_all_cases_predictions(all_cases_features):
    preds_df = pd.DataFrame(columns=ALL_CASES_PREDICTIONS_COLUMS)
    preds_df["TYPE"] = None
    
    all_cases_features,_,_,_,_ = process_data(x=all_cases_features, y=all_cases_features, 
                                              poly_features=poly_features, pca=pca, 
                                              OPTIMUM_DIMENSION=OPTIMUM_DIMENSION)
    
    mlp_preds = model.predict(all_cases_features.copy())
    mlp_preds = np.multiply(mlp_preds, 100)
    mlp_df = pd.DataFrame(mlp_preds, columns=ALL_CASES_PREDICTIONS_COLUMS)
    print(mlp_preds)
    mlp_df["TYPE"] = "MLP"
    preds_df = preds_df.append(mlp_df)
    
    rf_preds = forest_clf.predict(all_cases_features.copy())
    knn_preds = knn_clf.predict(all_cases_features.copy())
    sgd_preds = sgd_clf.predict(all_cases_features.copy())
    
    return preds_df

In [34]:
all_cases_predictions_df = get_all_cases_predictions(all_cases_features)

[[ 1.5532231 39.33496    6.9147215 ...  9.024629  14.086148   8.52484  ]
 [ 7.5096054 12.28265   13.228414  ...  8.306694   9.907604   6.382473 ]
 [ 3.334197  11.879541   8.093478  ...  7.020385   6.4445457  5.5389566]
 ...
 [10.774941   4.0829086 18.309965  ...  4.056551  13.190492   6.9754896]
 [58.334465   2.5842335  4.2555194 ...  3.2960277  9.138535   3.03973  ]
 [ 8.517955   5.9594374  7.3085656 ...  5.555501  45.96287    5.274289 ]]


In [35]:
all_cases_predictions_df

0          1          2          3          4          5  \
0     1.553223  39.334961   6.914721   4.262697   6.889342   3.366898   
1     7.509605  12.282650  13.228414   9.628992  18.349697   8.372885   
2     3.334197  11.879541   8.093478   9.054167  38.879452   3.876256   
3     4.830506   7.526378   4.747234  10.053899  44.879513   6.374301   
4     4.196395  13.264624   6.939872   4.464529   6.486824   6.161917   
5     7.192058   7.471269  18.833324   7.330932  11.896738   7.181845   
6     8.541879   6.164216   5.498583  15.079559  30.714527   4.132267   
7     6.336843   7.559615   5.517073  13.722263  24.713366   8.548863   
8     6.267414  16.135756  13.460493   7.860033   6.466064   9.541339   
9     9.336064   5.892505  23.692274  12.671237   6.915795  12.022660   
10   11.542850   8.172011  11.384916   9.412456  14.622158  10.376451   
11    9.220421   6.439025   8.997533   9.551017  10.147505  17.411613   
12   12.723465   6.444261  16.846584   5.617194   8.904403   5.707289   
13    6.125234   3.400927  45.686680   7.801488   5.670408   4.360641   
14   27.168417   5.192119   6.245614   9.108858  13.567047   4.806308   
15   12.434368   5.403138   6.919079   5.893281   7.730361   6.470235   
16    1.047108  55.071648   5.804783   6.204485   8.253347   1.883614   
17   10.878354  17.238192  11.413236   9.818634  22.666641   6.254408   
18    1.858342  12.367320  12.167258   8.149105  48.935528   2.368299   
19    7.599021   7.255278   6.148334   7.154451  49.044861   6.218117   
20    3.757053  24.159451  10.493711   6.944439   7.944014   6.380094   
21    6.877368  11.167678  12.850057   7.690183  18.197855   7.142544   
22    5.298155  11.547891  16.108614  11.319094  26.348236   4.943653   
23    8.233870  11.485835   7.099364   8.750209  26.461283   6.120478   
24    4.829028  19.518295  13.602885  13.100119   6.579478   9.224319   
25    9.949741   9.881509  12.364678  21.268501   7.473948  12.807820   
26   10.437007   7.289313  22.167244  10.674126  14.180244  10.678523   
27    9.182670   8.060501   9.262791   8.403986   9.760775  21.349201   
28   11.671268   7.874794  16.776707   5.385762   6.863308  10.542915   
29    7.944290   6.013651  15.995126   9.744460   7.793327   7.544936   
..         ...        ...        ...        ...        ...        ...   
98   10.450101   8.565024   5.794045   8.593863   6.467030   7.018950   
99    7.575533   6.045641   8.429304   9.969258   5.389151   9.154380   
100   6.228086   9.241343   6.089934  10.431414   5.193062   5.284709   
101   4.671368   5.138827  30.105162  12.986943   4.172295   6.166340   
102  32.092831   5.616095   4.243487  15.677229   7.228404   4.875949   
103   9.466213   6.530720   9.827697  12.563363   5.279297   8.389819   
104   5.490243  10.213663   9.039139  21.229248   5.404862   7.190260   
105   3.454418   4.235618  20.855801  36.885330   3.960310   4.865851   
106  18.326620   5.945343   7.204892   9.622448   7.126400   6.471156   
107   5.421726   4.252885   9.647815   8.220371   3.934496   6.239606   
108  16.703463   7.463532  16.631424  12.160860  10.156498   6.339450   
109   3.759735   2.873645  57.132416  11.348257   4.490664   3.397369   
110  62.629551   3.343482   3.769727   4.015837   5.129719   3.100262   
111   7.723270   7.487333  11.328348   6.775012   3.426826   4.493097   
112   2.858170   8.028877   3.874197   3.174693   2.931898   2.667173   
113   6.713665   8.311197   5.864713  22.637230   9.622909   8.228859   
114  10.243517   7.468194  11.160149   6.538281  11.918929   5.780048   
115   6.777427   7.431024   7.379228   9.964579  15.134950   9.481400   
116   7.553872   9.813243  11.986659   8.546484   5.807601   9.619576   
117   7.696512   7.017382  15.955670  14.165733   7.178235  12.415036   
118  23.459301   5.499379  12.005052  12.571282  10.579813   7.380401   
119   9.176565   8.237069  10.169098  10.549981   7.753926  10.453171   
120   7.109716   7.829186   5.947896  25.440025   9.084385   9.665501  